export const gridContainer = document.getElementById("grid");
export const playPauseButton = document.getElementById("playPause");
export const playIcon = document.getElementById("play");
export const pauseIcon = document.getElementById("pause");
export const safeZonePlacer = document.getElementById("safeZonePlacer");
export const mapContainer = document.getElementById("map");
export const getGridItems = () => document.querySelectorAll(".grid-item");
export const countdownClock = document.getElementById("countdownClock");
export const countdownTime = document.getElementById("countdownTime");
export const timebar = document.getElementById("timebar");
export const timer = document.getElementById("timer");
export const rootElement = document.documentElement;
